### ISSUE TITLE
Reintroduce tests with external services

### ISSUE THREAD

**Issue by heiglandreas** [laminas/laminas-diagnostics#75]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.25.x

#### Summary

Currently the test-setup uses quite some time and resources to setup all the required external services like redis, memcached and mongo but then the tests actually **using** these services are skipped.

I tried to add the tests during enabling PHP8.3 testing but all tests failed - not only the 8.3 ones but *all*.

So this is something that should be done separately.

I managed to add the tests by adding this code into the qa-job in `.github/workflows/continuous-integration.yml`:

```yml
    env:
      TESTS_LAMINAS_DIAGNOSTICS_MEMCACHE_ENABLED: true
      TESTS_LAMINAS_DIAGNOSTICS_MEMCACHED_ENABLED: true
      TESTS_LAMINAS_DIAGNOSTICS_MONGO_ENABLED: true
      TESTS_LAMINAS_DIAGNOSTICS_RABBITMQ_ENABLED: true
      TESTS_LAMINAS_DIAGNOSTICS_REDIS_ENABLED: true
```

#### Current behavior

All tests are failing

#### How to reproduce

Add the yml excerpt to the described file and let the tests run

#### Expected behavior

All tests green
